backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: https://teuespaco.com.br
display_url: https://teuespaco.com.br

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "noticias"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"

    meta:
      path:
        widget: "string"
        label: "Caminho do arquivo"
        index_file: "index"

    fields:
      - label: "Título"
        name: "title"
        widget: "string"

      - label: "Data"
        name: "date"
        widget: "string"
        default: "{{now | date('DD/MM/YYYY')}}"

      - label: "Categoria"
        name: "category"
        widget: "string"

      - label: "Imagem de capa"
        name: "thumbnail"
        widget: "image"
        required: false

      - label: "Conteúdo da notícia"
        name: "body"
        widget: "markdown"
