```yml
backend:
  name: git-gateway
  branch: main

identity_url: https://teuespaco.com.br/.netlify/identity
gateway_url: https://teuespaco.com.br/.netlify/git

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: https://teuespaco.com.br
display_url: https://teuespaco.com.br

collections:

  - name: "noticias"
    label: "Notícias"
    folder: "noticias"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"

    fields:
      - label: "Título"
        name: "title"
        widget: "string"

      - label: "Data"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
        format: "DD/MM/YYYY"
        time_format: false

      - label: "Categoria"
        name: "category"
        widget: "string"

      - label: "Imagem de capa"
        name: "thumbnail"
        widget: "image"
        required: false

      - label: "Galeria de Fotos"
        name: "gallery"
        widget: "list"
        required: false
        field:
          label: "Foto"
          name: "image"
          widget: "image"

      - label: "Conteúdo da notícia"
        name: "body"
        widget: "markdown"

  - name: "edicoes"
    label: "Edições"
    folder: "edicoes"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - label: "Título"
        name: "titulo"
        widget: "string"

      - label: "Link da edição"
        name: "link"
        widget: "string"

